### ISSUE TITLE
add cgraph

### ISSUE THREAD

**Issue by QiuYilin** [QiuYilin/vcpkg-registry#1]
Related issues https://github.com/ChunelFeng/CGraph/issues/324

**Comment by ChunelFeng** [comment]
Hi friend，what is going on ? 

Did it go well ?

**Comment by QiuYilin** [comment]
@ChunelFeng Sorry, I have been working on other things recently, and I will continue to do it when I have time. I think it should be enough to modify patch about add_libray() and install(). [新建自定义注册表](https://www.cnblogs.com/QiXiaoQiuRen/p/17968684)

**Comment by QiuYilin** [comment]
@ChunelFeng  cgraph port has been updated.
